### ISSUE TITLE
Implement /fly

### ISSUE THREAD

**Issue by NovaSquirrel** [NovaSquirrel/TilemapTown#57]
This command should toggle whether or not you can move through solid tiles and objects. I guess this could even be a client-side command because the server does not actually determine solidity of anything.

**Comment by pocketthemouse** [comment]
If this is just client-side, what do you think about adding it to the options menu?
![Screen Shot 2022-12-22 at 21 18 00](https://user-images.githubusercontent.com/120060732/209275788-c1099f1c-80bb-4427-833d-21a7c212a1d0.png)

Also, how should this interact with signs? Should you "read" them when you move onto them?

**Comment by NovaSquirrel** [comment]
That seems like a sensible place for it! And I didn't even think about signs; I guess that makes sense.
