### ISSUE TITLE
Typing notifications

### ISSUE THREAD

**Issue by NovaSquirrel** [NovaSquirrel/TilemapTown#63]
It can display a "..." above someone's head, and there's actually a graphic in the tileset potluck ( https://novasquirrel.com/town/img/potluck.png) that we can use for this if we want

**Comment by pocketthemouse** [comment]
Do you think this should be added as a boolean to `WHO` data or have its own commands?
It's a little silly to need to retransmit the whole `WHO` data if someone starts/stops typing, but there could be a new `WHO` type called `update` that just updates whatever properties are specified.
Like, when starting to type, the client could send `--> WHO {"update": {"id": id, "typing":true}}`, and the server would set `typing` to `true` for that player but leave their other attributes as-is. Then the server could rebroadcast that "delta" to clients, who receive `<-- WHO {"update": {"id": id, "typing":true}}` and then do the same thing.
It might get complicated to validate that the client should have permission to change whatever attributes it's trying to modify, though, especially if more stuff gets added to `WHO`.
Or there could be `<--> TYP {"id": id, "typing":true}` or something. If we did that then you wouldn't know that someone is typing if you join the map after they stop typing, but that doesn't seem like a big deal. The server probably doesn't even need to store whether someone is typing or not, really, it could just rebroadcast `TYP`s from the client.
I could go either way, but if you pick I can start on it!

**Comment by NovaSquirrel** [comment]
Feels silly since we're the only ones working on this, but documenting it here that we discussed the pros/cons on Discord and decided to go with continuing to treat `WHO` as a generic player status thing and adding it in there.
